name: flutterdoc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Icons et style iOS
  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^9.1.0

  # Code generation (freezed)
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0

  # Injection de dépendances
  get_it: ^8.0.3

  # Sérialisation JSON
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  pretty_dio_logger: ^1.4.0

  # Localisation
  intl: ^0.19.0
  easy_localization: ^3.0.7+1

  # Splash screen
  flutter_native_splash: ^2.4.4

  # SVG
  flutter_svg: ^2.1.0

  # Adaptation d’écran et taille de police
  flutter_screenutil: ^5.9.3

  # Générateur de build Dart
  build_runner: ^2.4.7

  # Firebase
  firebase_core: ^2.27.0

  # Images mises en cache
  cached_network_image: ^3.3.1

  # Stockage simple et sécurisé
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Effet shimmer
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

