default_platform(:android)

platform :android do
  desc "lane for Android firebase app distribution"
  lane :firebase_distribution do
    # Build Flutter
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    
    # Distribution Firebase avec plugin
    firebase_app_distribution(
      app: "1:1032200431495:android:367c351d3396ce57521522",
      apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      testers: "myahmedelamiri@gmail.com,lailaelamiri586@gmail.com",
      release_notes: "First Distribution from Fastlane - #{Time.now.strftime('%Y-%m-%d %H:%M')}",
      debug: true
    )
    
    puts "✅ Successfully deployed to Firebase App Distribution!"
  end
end